<?php

namespace EP\UploadBundle\Entity;

/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends \Doctrine\ORM\EntityRepository
{

    public function count($user){
        $queryBuilder = $this->createQueryBuilder('f')
            ->select('count(f)')
            ->andwhere("f.owner = :owner")
            ->setParameter("owner",$user);
        return $queryBuilder->getQuery()->getSingleScalarResult();   
    }
}
