<?php

namespace EP\UploadBundle\Entity;

/**
 * FilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSearchQuery($user, $search = "", $orderby = "name", $order = "ASC", $categoryFilter = "", $extFilter = "") 
    {
        $queryBuilder = $this->createQueryBuilder('f');
        $parameters = array();

        $queryBuilder->andwhere("f.owner = :owner");
        $parameters["owner"] = $user;

        if ("" !== $search) {
            $queryBuilder->andwhere("f.name LIKE :name");
                // ->setParameter('name', '%'.$search.'%');
            $parameters['name'] = '%'.$search.'%';
        }

        if ("" !== $categoryFilter) {
            $queryBuilder->andwhere("f.category = :category");
                // ->setParameter('category', $categoryFilter);
            $parameters['category'] = $categoryFilter;
        }

        if ("" !== $extFilter) {
            $queryBuilder->andwhere("f.ext = :ext");
                // ->setParameter('ext', $extFilter);
            $parameters['ext'] = $extFilter;
        }

        $queryBuilder->setParameters($parameters);

        $queryBuilder->orderBy("f.".$orderby, $order);

        $query = $queryBuilder->getQuery();

        return $query;
    }

    public function findLast($user)
    {
        $queryBuilder = $this->createQueryBuilder('f')
            ->andwhere("f.owner = :owner")
            ->setParameter("owner",$user)
            ->orderby("f.date","DESC")
            ->setMaxResults(5);

        return $queryBuilder->getQuery()->getResult();
    }
}