<?php

namespace EP\UploadBundle\Entity;

/**
 * FilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithParameters($search = null, $orderby = "name", $filers = array()) 
    {
        $queryBuilder = $this->createQueryBuilder('f');

        if (null !== $search) {
            $queryBuilder->where("f.name LIKE :name")
                ->setParameter('name', '%'.$search.'%');
        }

        

        $queryBuilder->orderBy("f.".$orderby);

        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }
}