<?php

namespace EP\UploadBundle\Entity;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByField($field, $value, $user)
    {
        $qb = $this->createQueryBuilder('p');
        $parameters = array();

        $qb->andwhere("p.owner = :owner");
        $parameters["owner"] = $user;

        if (null !== $field && null !== $value) {
            $qb->andwhere("p.".$field." LIKE :value");
            $parameters["value"] = "%".$value."%";
        }

        $qb->setParameters($parameters);

        return $qb->getQuery()->getResult();
    }

    public function findLast($user)
    {
        $queryBuilder = $this->createQueryBuilder('p')
            ->andwhere("p.owner = :owner")
            ->setParameter("owner",$user)
            ->setMaxResults(5);

        return $queryBuilder->getQuery()->getResult();
    }

    public function count(){
        $queryBuilder = $this->createQueryBuilder('p')
            ->select('count(p)');
        return $queryBuilder->getQuery()->getSingleScalarResult();   
    }
}
