ep_upload_home:
    path:    /
    defaults: { _controller:EPUploadBundle:Upload:index }

ep_upload_file:
    path: /upload
    defaults: { _controller:EPUploadBundle:Upload:upload }

ep_delete_file:
    path: /delete/{id}
    defaults: { _controller:EPUploadBundle:Upload:delete}
    requirements:
        id: \d+

ep_view_file:
    path: /list
    defaults: { _controller:EPUploadBundle:Upload:list }