ep_upload_home:
    path:    /dispatch
    defaults: { _controller:EPUploadBundle:Upload:index }

ep_user_homepage:
    path:    /
    defaults: { _controller:EPUploadBundle:Upload:home }

ep_upload_file:
    path: /upload
    defaults: { _controller:EPUploadBundle:Upload:upload }

ep_delete_file:
    path: /delete/{id}
    defaults: { _controller:EPUploadBundle:Upload:delete}
    requirements:
        id: \d+

ep_view_file:
    path: /list
    defaults: { _controller:EPUploadBundle:Upload:list }

ep_download_file:
    path: /download/{fileId}
    defaults: { _controller:EPUploadBundle:Upload:download }
    requirements:
        fileId: \d+

ep_edit_fact:
    path: /edit
    defaults: { _controller:EPUploadBundle:Facture:edit }

ep_show_client:
    path: /clients
    defaults: { _controller:EPUploadBundle:Client:show }

ep_edit_client:
    path: /client/new
    defaults: { _controller:EPUploadBundle:Client:create }

ep_delete_client:
    path: /client/delete/{id}
    defaults: { _controller: EPUploadBundle:Client:delete }

ep_modify_client:
    path: /client/edit/{id}
    defaults: { _controller: EPUploadBundle:Client:edit }

ep_show_produit:
    path: /produits
    defaults: { _controller:EPUploadBundle:Produit:show }

ep_edit_produit:
    path: /produit/new
    defaults: { _controller:EPUploadBundle:Produit:create }

ep_delete_produit:
    path: /produit/delete/{id}
    defaults: { _controller: EPUploadBundle:Produit:delete }

ep_modify_produit:
    path: /produit/edit/{id}
    defaults: { _controller: EPUploadBundle:Produit:edit }

ep_messages:
    path:     /messages/{id}
    defaults: { _controller: EPUploadBundle:Messages:messages, id: null }

ep_send_message:
    path:     /admin/send
    defaults: { _controller: EPUploadBundle:Messages:sendMessage }

ep_download_untreated:
    path: /download/untreated/{username}
    defaults: { _controller: EPUploadBundle:Upload:downloadUntreated }

rest_create_client:
    path: /rest/client/create
    defaults: { _controller: EPUploadBundle:Client:createRest }