ep_upload_home:
    path:    /home
    defaults: { _controller:EPUploadBundle:Upload:index }

ep_upload_file:
    path: /file
    defaults: { _controller:EPUploadBundle:Upload:upload }

ep_delete_file:
    path: /delete/{id}
    defaults: { _controller:EPUploadBundle:Upload:delete}
    requirements:
        id: \d+