ep_upload_home:
    path:    /
    defaults: { _controller:EPUploadBundle:Upload:index }

ep_upload_file:
    path: /upload
    defaults: { _controller:EPUploadBundle:Upload:upload }

ep_delete_file:
    path: /delete/{id}
    defaults: { _controller:EPUploadBundle:Upload:delete}
    requirements:
        id: \d+

ep_view_file:
    path: /list
    defaults: { _controller:EPUploadBundle:Upload:list }

ep_download_file:
    path: /download/{fileId}
    defaults: { _controller:EPUploadBundle:Upload:download }
    requirements:
        fileId: \d+

ep_edit_fact:
    path: /edit
    defaults: { _controller:EPUploadBundle:Facture:edit }

ep_show_client:
    path: /clients
    defaults: { _controller:EPUploadBundle:Client:show }

ep_edit_client:
    path: /client/new
    defaults: { _controller:EPUploadBundle:Client:edit }

ep_show_produit:
    path: /produits
    defaults: { _controller:EPUploadBundle:Produit:show }

ep_edit_produit:
    path: /produit/new
    defaults: { _controller:EPUploadBundle:Produit:edit }
