<?php

namespace AppBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function countUntreated() 
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u.username, COUNT(f.id)')
            ->join('EPUploadBundle:Files','f', 'WITH','f.owner = u')
            ->where('f.treated IS NULL')
            ->groupBy('f.owner');

        return $qb->getQuery()->getResult();
    }
}
